import { Footer } from '@/components/layout/Footer/Footer'
import { InfoBanner } from '@/components/layout/infoBanner/InfoBanner'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import './normalize.scss'

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
	title: 'Семейная школа',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={'bg-[#ffffff] ' + roboto.className}>
				<InfoBanner />
				{children}
				<Footer />
			</body>
		</html>
	)
}
